# Generated by Django 6.0.3 on 2026-04-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('ultrasound', 'Ultrasound'), ('xray', 'X-Ray'), ('pregnancy', 'Pregnancy Scan')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
